[package]
name = "textfilebusy"
version = "0.1.0"
authors = ["Hans-Christian Esperer <hc@caiberp.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "*"
tempfile = "*"
